name: CI/CD Pipeline - Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    name: Set up Python & Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      python-cache-key: ${{ steps.cache-pip.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-django

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - uses: actions/checkout@v3
      - run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup-python
    steps:
      - uses: actions/checkout@v3
      - run: pytest --ds=core.settings --cov=.

  docker_build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker build --pull --cache-from=${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - run: |
          curl --fail -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/deploy/srv-d37gdk1r0fns739fsdkg
